POINT/Source/Point.MVC.Reporting/Controllers/LookUpController.cs
using Point.Business.Helper;
using Point.Business.Logic;
using Point.Database.Context;
using Point.Database.Models;
using Point.Models.Enums;
using Point.Database.Repository;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Point.MVC.Reporting.Controllers
{
    [Authorize]
    public class LookUpController : Controller
    {
        private readonly UnitOfWork<PointContext> uow = new UnitOfWork<PointContext>();

        public JsonResult GetFlowDefinitions(int reportDefinitionID)
        {
            var reportdefinition = ReportDefinitionBL.GetByReportDefinitionID(uow, reportDefinitionID);
            var pointuserinfo = PointUserInfoHelper.GetPointUserInfo(uow);
            var maxlevel = pointuserinfo.GetReportFunctionRoleLevelID();

            var flowdefinitions = new List<FlowDefinition>();
            if(maxlevel > FunctionRoleLevelID.Organization)
            {
                flowdefinitions = FlowDefinitionBL.GetActiveFlowDefinitions(uow).ToList();
            } else if(maxlevel == FunctionRoleLevelID.Organization)
            {
                flowdefinitions = FlowDefinitionParticipationBL.GetByOrganizationIDs(uow, pointuserinfo.EmployeeOrganizationIDs)
                    .Where(p => reportdefinition.ReportDefinitionFlowDefinition.Any(rfd => 
                            rfd.FlowDefinitionID == p.FlowDefinitionID &&
                            reportdefinition.FlowDirection == FlowDirection.Any || p.FlowDirection == FlowDirection.Any || reportdefinition.FlowDirection == p.FlowDirection
                    ))
                    .Select(p => p.FlowDefinition)
                    .Distinct()
                    .ToList();
            }
            else if (maxlevel <= FunctionRoleLevelID.Location)
            {
                flowdefinitions = FlowDefinitionParticipationBL.GetByLocationIDs(uow, pointuserinfo.EmployeeLocationIDs)
                    .Where(p => reportdefinition.ReportDefinitionFlowDefinition.Any(rfd =>
                            rfd.FlowDefinitionID == p.FlowDefinitionID &&
                            reportdefinition.FlowDirection == FlowDirection.Any || p.FlowDirection == FlowDirection.Any || reportdefinition.FlowDirection == p.FlowDirection
                    ))
                    .Select(p => p.FlowDefinition)
                    .Distinct()
                    .ToList();
            }

            return Json(
                flowdefinitions.Select(f => new {
                    f.FlowDefinitionID,
                    f.Name
                }).OrderBy(f => f.FlowDefinitionID), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetReportDefinition(int reportDefinitionID)
        {
            var reportdefinition = ReportDefinitionBL.GetByReportDefinitionID(uow, reportDefinitionID);

            return Json(
                new {
                    reportdefinition.ReportName,
                    reportdefinition.ReportActionName,
                    reportdefinition.FileName,
                    reportdefinition.ExcelFriendlyFileName,
                    reportdefinition.FilterPartial
                }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetReportOrganizationsByRegionIDAndOrganizationTypes(int regionID, OrganizationTypeID[] organizationTypeIDs = null)
        {
            var pointuserinfo = PointUserInfoHelper.GetPointUserInfo(uow);
            var maxlevel = pointuserinfo.GetReportFunctionRoleLevelID();
            var organizationlist = OrganizationBL.GetActiveByRegionID(uow, regionID);

            if (maxlevel < FunctionRoleLevelID.Region)
            {
                organizationlist = organizationlist.Where(org => pointuserinfo.EmployeeOrganizationIDs.Contains(org.OrganizationID));
            }

            if(organizationTypeIDs != null)
            {
                organizationlist = organizationlist.Where(org => organizationTypeIDs.Contains((OrganizationTypeID)org.OrganizationTypeID));
            }

            return Json(
                organizationlist.Select(org => new {
                    org.OrganizationID,
                    org.Name
                }).OrderBy(loc => loc.Name), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetReportLocationsByOrganizationIDs(int[] organizationIDs)
        {
            var pointuserinfo = PointUserInfoHelper.GetPointUserInfo(uow);
            var maxlevel = pointuserinfo.GetReportFunctionRoleLevelID();
            IEnumerable<Location> locationlist = null;

            locationlist = LocationBL.GetActiveByOrganisationIDs(uow, organizationIDs);
            if (maxlevel <= FunctionRoleLevelID.Location && organizationIDs.All(orgid => pointuserinfo.EmployeeOrganizationIDs.Contains(orgid)))
            {
                locationlist = locationlist.Where(loc => pointuserinfo.EmployeeLocationIDs.Contains(loc.LocationID));
            }

            return Json(
                locationlist.Select(loc => new {
                    loc.LocationID,
                    Name = loc.FullName()
                }).OrderBy(loc => loc.Name), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetReportDepartmentsByLocationIDs(int[] locationIDs)
        {
            var pointuserinfo = PointUserInfoHelper.GetPointUserInfo(uow);
            var maxlevel = pointuserinfo.GetReportFunctionRoleLevelID();
            IEnumerable<Department> departmentlist = null;

            departmentlist = DepartmentBL.GetAllActiveByLocationIDs(uow, locationIDs.ToList());
            if (maxlevel < FunctionRoleLevelID.Location)
            {
                departmentlist = departmentlist.Where(dep => pointuserinfo.EmployeeDepartmentIDs.Contains(dep.DepartmentID));
            }

            return Json(
                departmentlist.Select(dep => new {
                    dep.DepartmentID,
                    Name = dep.FullName()
                }).OrderBy(loc => loc.Name), JsonRequestBehavior.AllowGet);
        }
    }
}

POINT/Source/Point.MVC.Reporting/Controllers/ReportingController.cs
using Microsoft.Reporting.WebForms;
using Point.Business.Helper;
using Point.Business.Logic;
using Point.Database.Context;
using Point.Database.Models.ReportModels;
using Point.Database.Repository;
using Point.Infrastructure;
using Point.Infrastructure.Extensions;
using Point.Models.Enums;
using Point.Models.ViewModels;
using Point.MVC.Reporting.DataSources;
using Point.MVC.Reporting.Helpers;
using Point.MVC.Reporting.Logic;
using Point.MVC.Reporting.Models.ViewModels;
using Point.ServiceBus.Models;
using System;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using System.Xml;
using System.Xml.Serialization;

namespace Point.MVC.Reporting.Controllers
{
    [Authorize]
    [OutputCache(NoStore = true, Duration = 0)]
    public class ReportingController : WebApplication.Controllers.PointBaseController
    {
        DateTime defaultStartDate = new DateTime(DateTime.Now.Year, 1, 1).AddYears(-1);
        DateTime defaultEndDate = new DateTime(DateTime.Now.Year, 1, 1).AddYears(1).AddMinutes(-1);

        public ActionResult Index(int? reportDefinitionID = null)
        {
            var unitofwork = new UnitOfWork<PointContext>();
            var pointuserinfo = PointUserInfoHelper.GetPointUserInfo(unitofwork);

            ReportingViewModel viewmodel = null; 

            var view = "Index";

            if(reportDefinitionID.HasValue)
            {
                var reportdefinition = ReportDefinitionBL.GetByReportDefinitionID(uow, reportDefinitionID.Value);

                viewmodel = FilterViewModelBL.GetNew(defaultStartDate, defaultEndDate, pointuserinfo, reportdefinition.ReportName);

                view = "IndexDirect";
                viewmodel.ReportDefinitionID = reportDefinitionID.Value;
                viewmodel.ReportActionName = reportdefinition?.ReportActionName;
                viewmodel.Name = reportdefinition?.ReportName;
            } else
            {
                viewmodel = FilterViewModelBL.GetNew(defaultStartDate, defaultEndDate, pointuserinfo, "");
            }

            return View(view, viewmodel);
        }

        public ActionResult XMLDump(int? year = null)
        {
            var unitofwork = new UnitOfWork<PointContext>();
            var pointuserinfo = PointUserInfoHelper.GetPointUserInfo(unitofwork);

            FilterViewModel viewmodel = null;

            if(year.HasValue)
            {
                viewmodel = FilterViewModelBL.GetNew(new DateTime(year.Value, 1, 1), new DateTime(year.Value + 1, 1, 1).AddDays(-1), pointuserinfo, "Dump");
            } else
            {
                viewmodel = FilterViewModelBL.GetNew(defaultStartDate, defaultEndDate, pointuserinfo, "Dump");
            }

            var dumpreportmodellist = new DumpReportModelList()
            {
                Items = ReportModelBL.GetDumpReportData(viewmodel, pointuserinfo)
            };

            var builder = new StringBuilder();
            using (var xmlWriter = XmlWriter.Create(builder))
            {
                var serializer = new XmlSerializer(dumpreportmodellist.GetType());
                serializer.Serialize(xmlWriter, dumpreportmodellist);

                return Content(builder.ToString(), "text/xml");
            }
        }

        public ActionResult CSVDump(FilterViewModel viewmodel)
        {
            ServiceBusBL.SendMessage(uow, "CSVDump", "CSVDumpRequest", new CSVDumpRequest()
            {
                FlowDirection = FlowDirection.Any,
                UniqueID = DateTime.Now.Ticks,
                TimeStamp = DateTime.Now,
                EmployeeID = PointUserInfo().Employee.EmployeeID,
                Filter = viewmodel
            });

            return View("CSVAsync");
        }

        public ActionResult InStroomDumpReport(ReportingViewModel viewmodel)
        {
            return ReportView(
                "Report",
                ReportViewModelBL.GetByFilterViewModelAndDataSource(
                    viewmodel,
                    ReportDataSources.GetInStroomDumpReportData(viewmodel)
                ));
        }

        public ActionResult UitStroomDumpReport(ReportingViewModel viewmodel)
        {
            return ReportView(
                "Report",
                ReportViewModelBL.GetByFilterViewModelAndDataSource(
                    viewmodel,
                    ReportDataSources.GetUitStroomDumpReportData(viewmodel)
                ));
        }

        public ActionResult InstroomReportLocatie(ReportingViewModel viewmodel)
        {
            return ReportView(
                "Report",
                ReportViewModelBL.GetByFilterViewModelAndDataSource(
                    viewmodel,
                    ReportDataSources.GetInstroomReportData(viewmodel)
                ));
        }

        public ActionResult InstroomReportOverzicht(ReportingViewModel viewmodel)
        {
            return ReportView(
                "Report",
                ReportViewModelBL.GetByFilterViewModelAndDataSource(
                    viewmodel,
                    ReportDataSources.GetInstroomReportData(viewmodel)
                ));
        }

        public ActionResult InstroomReportIndicerend(ReportingViewModel viewmodel)
        {
            return ReportView(
                "Report",
                ReportViewModelBL.GetByFilterViewModelAndDataSource(
                    viewmodel,
                    ReportDataSources.GetInstroomReportData(viewmodel)
                ));
        }

        public ActionResult InStroomAantallenPerMaand(ReportingViewModel viewmodel)
        {
            return ReportView(
                "Report",
                ReportViewModelBL.GetByFilterViewModelAndDataSource(
                    viewmodel,
                    ReportDataSources.GetInstroomReportData(viewmodel)
                ));
        }

        public ActionResult InStroomTop10Report(ReportingViewModel viewmodel)
        {
            return ReportView(
                "Report",
                ReportViewModelBL.GetByFilterViewModelAndDataSource(
                    viewmodel,
                    ReportDataSources.GetInStroomTop10ReportData(viewmodel)
                ));
        }

        public ActionResult InStroomZorgType(ReportingViewModel viewmodel)
        {
            return ReportView(
                "Report",
                ReportViewModelBL.GetByFilterViewModelAndDataSource(
                    viewmodel,
                    ReportDataSources.GetInstroomReportData(viewmodel)
                ));
        }

        public ActionResult InStroomOntslagDatumGepasseerd(ReportingViewModel viewmodel)
        {
            return ReportView(
                "Report",
                ReportViewModelBL.GetByFilterViewModelAndDataSource(
                    viewmodel,
                    ReportDataSources.GetInStroomOntslagDatumGepasseerdReportData(viewmodel)
                ));
        }

        public ActionResult InStroomOntslagDatumBehaaldReport(ReportingViewModel viewmodel)
        {
            return ReportView(
                "Report",
                ReportViewModelBL.GetByFilterViewModelAndDataSource(
                    viewmodel,
                    ReportDataSources.GetInStroomOntslagDatumBehaaldReportData(viewmodel)
                ));
        }

        public ActionResult InStroomVKBReport(ReportingViewModel viewmodel)
        {
            return ReportView(
                "Report",
                ReportViewModelBL.GetByFilterViewModelAndDataSource(
                    viewmodel,
                    ReportDataSources.GetInStroomVKBReportData(viewmodel)
                ));
        }

        public ActionResult InStroomProcesTijdenReport(ReportingViewModel viewmodel)
        {
            return ReportView(
                "Report",
                ReportViewModelBL.GetByFilterViewModelAndDataSource(
                    viewmodel,
                    ReportDataSources.GetInStroomProcesTijdenReportData(viewmodel)
                ));
        }

        public ActionResult InStroomKPIInBehandelingReport(KPIFilterViewModel viewmodel)
        {
            return ReportView(
                "Report",
                ReportViewModelBL.GetByFilterViewModelAndDataSource(
                    viewmodel,
                    ReportDataSources.GetInStroomKPIInBehandelingReportData(viewmodel)
                ));
        }

        public ActionResult InStroomKPITerugmeldingReport(KPIFilterViewModel viewmodel)
        {
            return ReportView(
                "Report",
                ReportViewModelBL.GetByFilterViewModelAndDataSource(
                    viewmodel,
                    ReportDataSources.GetInStroomKPITerugmeldingReportData(viewmodel)
                ));
        }

        public ActionResult InStroomUitvalReport(ReportingViewModel viewmodel)
        {
            return ReportView(
                "Report",
                ReportViewModelBL.GetByFilterViewModelAndDataSource(
                    viewmodel,
                    ReportDataSources.GetInStroomUitvalReportData(viewmodel)
                ));
        }

        public ActionResult InStroomWaarIsDePatientGebleven(ReportingViewModel viewmodel)
        {
            return ReportView(
                "Report",
                ReportViewModelBL.GetByFilterViewModelAndDataSource(
                    viewmodel,
                    ReportDataSources.GetInStroomWaarIsDePatientGebleven(viewmodel)
                ));
        }

        public ActionResult InStroomTotalenReport(ReportingViewModel viewmodel)
        {
            return ReportView(
                "Report",
                ReportViewModelBL.GetByFilterViewModelAndDataSource(
                    viewmodel,
                    ReportDataSources.GetInStroomTotalenReportData(viewmodel)
                ));
        }

        public ActionResult UitstroomReportLocatie(ReportingViewModel viewmodel)
        {
            return ReportView(
                "Report",

POINT/Source/Point.MVC.Reporting/Views/Reporting/CSVAsync.cshtml
<h3>Uw dumpbestand wordt gegenereerd</h3> 

U ontvangt een bericht in uw emailbox wanneer het bestand is gegenereerd.

POINT/Source/Point.MVC.Reporting/Views/Reporting/Index.cshtml
@using Point.MVC.Reporting.Models.ViewModels
@model ReportingViewModel

@{
    var target = "_self";
}

<style type="text/css">
    .multiselect.btn {
        text-align: left;
    }

    .caret {
        float: right;
        margin: 8px 0;
    }

    .reportselection {
        position: relative;
        display: block;
        border: 1px solid #d0d0d0;
        border-radius: 5px;
        padding: 5px;
        padding-right: 25px;
        margin-bottom: 8px;
        min-height: 38px;
        /*min-height: 76px;*/
    }

        .reportselection label {
            font-weight: bold !important;
        }

    .topright {
        position: absolute;
        top: 5px;
        right: 5px;
    }

    select.multiple {
        opacity: 0;
        position: absolute;
        max-height: 27px;
        max-width: 160px;
    }

    #modal .modal-body {
        white-space: pre-wrap;
    }
</style>

@section Scripts
{
<script type="text/javascript">
    $.validator.setDefaults({ ignore: '.ignore *' });

    function ShowModal(message, header) {
        $("#modal .modal-body").html(message);
        if (header) {
            $("#modal .modal-title").html(header);
        }
        $("#modal").modal({backdrop: false, keyboard: true});
    }

    function Popup(element) {
        ShowModal($(element).data("description"), $(element).data("name"));
    }

    $(function () {
        $('.nav-tabs a, #nextButton, #previousButton').on('show.bs.tab', function (event) {
            var href = $(event.target).attr("href");
            var disabled = $(event.target).attr("disabled") === "disabled";
            if (disabled) {
                event.preventDefault();
                return;
            }

            $('.nav-tabs li').removeClass("active");
            $('.nav-tabs a[href="' + href + '"]').closest("li").addClass("active");
        });

        ResetControls();
    });

    function ResetControls() {
        $('select.multiple').multiselect({
            nonSelectedText: 'Alle (geen filter)&nbsp;',
            nSelectedText: 'geselecteerd',
            maxHeight: 200,
            numberDisplayed: 1,
            //disableIfEmpty: true
        });

        $('select.multiple').removeAttr('style');

        $('.date').datetimepicker({
            format: 'L',
            locale: 'nl',
            useCurrent: false
        });
    }

    function LoadFilter(reportdefinitionid) {
        var url = '@Url.Action("GetFilter", "Reporting")';
        $.ajax({
            url: url,
            data: { reportdefinitionid: reportdefinitionid },
            success: function (data, status, jqxhr) {
                $("#filtercontainer").html(data);

                var form = $("#reportForm");
                form.removeData("validator").removeData("unobtrusiveValidation");

                var needsOrganization = form.find("#NeedsOrganizationID").val() === "True";
                if (needsOrganization === false) {
                    form.find("#OrganizationIDs").removeAttr("data-val-required").removeAttr("data-val");
                }

                ResetControls();

                initializevalidation(form);
                $.validator.unobtrusive.parse(form);
            }
        });
    }

    function ShowLoader() {
        if ($("#reportForm").valid()) {
            $('#loader').modal('show')
        }
    }

    function ChangeReport(sender) {
        var url = '@Url.Action("GetReportDefinition", "LookUp")';
        var reportDefinitionID = $(sender).val();
        if (reportDefinitionID === '') return;

        $("#nextTab,#nextButton").removeAttr("disabled");

        $.ajax({
            dataType: "json",
            cache: false,
            url: url,
            data: { ReportDefinitionID: reportDefinitionID },
            success: function(data, status, jqxhr)
            {
                LoadFilter(reportDefinitionID)

                var showexcelcheckbox = data.ExcelFriendlyFileName !== '';
                var showcsvcheckbox = data.ExcelFriendlyFileName === '' && data.FileName === '';
                var showreportcheckbox = data.FileName !== '';

                $("#UseCSVFriendly").toggle(showcsvcheckbox).closest(".form-group").toggle(showcsvcheckbox || showexcelcheckbox || showreportcheckbox);
                $("#UseExcelFriendly").toggle(showexcelcheckbox).closest(".form-group").toggle(showcsvcheckbox || showexcelcheckbox || showreportcheckbox);
                $("#UseReport").toggle(showreportcheckbox).closest(".form-group").toggle(showcsvcheckbox || showexcelcheckbox || showreportcheckbox);

                $("form").prop("action", data.ReportActionName);
            }
        });

        $("#FlowDefinitionIDs").find("option").remove();
        $('#FlowDefinitionIDs').multiselect('rebuild');
        var urlflows = '@Url.Action("GetFlowDefinitions", "LookUp")';
        $.ajax({
            dataType: "json",
            url: urlflows,
            data: { ReportDefinitionID: reportDefinitionID },
            success: function (data, status, jqxhr) {
                $.each(data, function (index, row) {
                    $("#FlowDefinitionIDs").append($('<option>', { value: row.FlowDefinitionID }).text(row.Name));
                });
                $('#FlowDefinitionIDs').multiselect('rebuild');
            }
        });
    }

    function ChangeOrganizationTypeID(sender) {
        $("#RegionID").val('');
        $("#OrganizationIDs, #LocationIDs, #DepartmentIDs, #CompareDepartmentIDs").find("option").remove();
        $("#OrganizationIDs, #LocationIDs, #DepartmentIDs, #CompareDepartmentIDs").multiselect('rebuild');
    }

    function ChangeRegion(sender) {
        $("#OrganizationIDs option").remove();

        var url = '@Url.Action("GetReportOrganizationsByRegionIDAndOrganizationTypes", "LookUp")';
        var regionID = $(sender).val();
        if (regionID === null) {
            $('#OrganizationIDs').multiselect('rebuild');
            return;
        }

        $.ajax({
            url: url,
            type: 'POST',
            data: $("#RegionID, #OrganizationTypeIDs").serialize(),
            success: function (data, status, jqxhr) {
                $.each(data, function (index, row) {
                    $("#OrganizationIDs").append($('<option>', { value: row.OrganizationID }).text(row.Name));
                });
                $('#OrganizationIDs').multiselect('rebuild');
            }
        });
    }

    function ChangeOrganization(sender) {
        $("#LocationIDs option").remove();

        var url = '@Url.Action("GetReportLocationsByOrganizationIDs", "LookUp")';
        var organizationIDs = $(sender).val();
        if (organizationIDs === null) {
            $('#LocationIDs').multiselect('rebuild');
            return;
        }

        //trigger validation
        $("#reportForm").valid()

        $.ajax({
            url: url,
            type: 'POST',
            data: $(sender).serialize(),
            success: function (data, status, jqxhr) {
                $.each(data, function (index, row) {
                    $("#LocationIDs").append($('<option>', { value: row.LocationID }).text(row.Name));
                });
                $('#LocationIDs').multiselect('rebuild');
            }
        });
    }

    function ChangeLocation(sender) {
        $("#DepartmentIDs option, #CompareDepartmentIDs option").remove();

        var url = '@Url.Action("GetReportDepartmentsByLocationIDs", "LookUp")';
        var locationIDs = $(sender).val();
        if (locationIDs === null) {
            $('#DepartmentIDs, #CompareDepartmentIDs').multiselect('rebuild');
            return;
        }

        $.ajax({
            url: url,
            type: 'POST',
            data: $(sender).serialize(),
            success: function (data, status, jqxhr) {
                $.each(data, function (index, row) {
                    $("#DepartmentIDs, #CompareDepartmentIDs").append($('<option>', { value: row.DepartmentID }).text(row.Name));
                });
                $('#DepartmentIDs, #CompareDepartmentIDs').multiselect('rebuild');
            }
        });
    }
</script>
}

@using (Html.BeginForm("Index", "Reporting", FormMethod.Post, htmlAttributes: new { target = target, @class = "form-horizontal", action = Model.ReportActionName, id = "reportForm"}))
{
    @Html.HiddenFor(m => m.UseExcel)
    @Html.HiddenFor(m => m.UseCSV)
    <div id="reportTabs">
        <ul class="nav nav-tabs" role="tablist" style="margin-bottom: 3px;">
            <li class="active">
                <a href="#reportChoice" data-toggle="tab">Rapportkeuze</a>
            </li>
            <li>
                <a id="nextTab" href="#reportFilter" data-toggle="tab" disabled="disabled">Filter</a>
            </li>
        </ul>
        <div class="tab-content clearfix">
            <div class="tab-pane active" id="reportChoice">
                <div class="panel panel-default">
                    <div class="panel-body">
                        @foreach (var group in Model.ReportGroups)
                        {
                            <b>@group.Key</b>
                            <div class="row">
                                @foreach (var item in group.Value.OrderBy(v => v.Name))
                                {
                                    <div class="col-sm-4 col-md-3">
                                        <div class="reportselection bg-lightblue">
                                            <label class="cursor-pointer text-nowrap" style="overflow:hidden;">
                                                <input type="radio" name="ReportDefinitionID" required value="@item.ID" onchange="ChangeReport(this)" /> @item.Name
                                            </label>
                                            <span class="topright cursor-pointer glyphicon glyphicon-info-sign" onclick="Popup(this)" data-name="@group.Key - @item.Name" data-description="@item.Description"></span>
                                        </div>
                                    </div>
                                }
                            </div>
                        }
                    </div>
                    <div class="panel-footer">
                        <div class="form-group row">
                            <div class="col-xs-12 text-right">
                                <a id="nextButton" href="#reportFilter" class="btn btn-primary" data-toggle="tab" disabled="disabled">Volgende</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="reportFilter">
                <div class="panel panel-default">
                    <div class="panel-body" id="filtercontainer">
                        @Html.Partial("_DefaultFilter", Model)
                    </div>
                    <div class="panel-footer">
                        <div class="form-group row">
                            <div class="col-xs-6 text-left">
                                <a id="previousButton" href="#reportChoice" class="btn btn-default" data-toggle="tab">Vorige</a>
                            </div>
                            <div class="col-xs-6 text-right">
                                <input type="submit" id="UseCSVFriendly" value="CSV" onclick="$('#UseCSV').val(true); $('form').prop('target', '');" class="btn btn-default" />
                                <input type="submit" id="UseExcelFriendly" value="Excel" onclick="$('#UseExcel').val(true); $('form').prop('target', '');" class="btn btn-default" />
                                <input type="submit" id="UseReport" value="Rapport" onclick="ShowLoader(); $('#UseExcel, #UseCSV').val(false); $('form').prop('target', '@target');" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div class="modal" data-backdrop="false" role="dialog" id="loader" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-body">
                <div style="height:100px;">
                    <img style="float:left;margin-right:20px;height:100px" src="@Url.Content("~/Content/Images/PointLoading.gif")" />
                    <br />
                    Even geduld a.u.b.
                </div>
            </div>
        </div>
    </div>
</div>

POINT/Source/Point.MVC.Reporting/Views/Reporting/Report.cshtml
@using Point.MVC.Reporting.Models.ViewModels
@model ReportingOutputViewModel
@using ReportViewerForMvc
@using Microsoft.Reporting.WebForms
@{
    var reportviewer = new ReportViewer();
    reportviewer.Visible = true;
    reportviewer.AsyncRendering = false;
    reportviewer.SizeToReportContent = true;
    reportviewer.ProcessingMode = ProcessingMode.Local;
    reportviewer.HyperlinkTarget = "_blank";
    reportviewer.LocalReport.ReportPath = Model.ReportFileName;
    reportviewer.LocalReport.DataSources.Add(Model.ReportDataSource);
    var parameters = reportviewer.LocalReport.GetParameters().AsQueryable();

    foreach (var reportParameter in Model.ReportParameters)
    {
        if (parameters.Any(p => p.Name == reportParameter.Name))
        {
            reportviewer.LocalReport.SetParameters(reportParameter);
        }
    }

    reportviewer.LocalReport.Refresh();

    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Point - @Model.ReportName</title>
    <style>
        html, body {
            height: 100%;
            padding: 0;
            margin: 0;
        }

        iframe {
            /*for the report viewer*/
            border: none;
            padding: 0;
            margin: 0;
            width: 100%;
            height: 99%;
        }
    </style>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
</head>
<body>
    @Html.ReportViewer(reportviewer)
</body>
</html>