POINT/Source/Point.MVC.WebApplication/Controllers/ContactInformationController.cs
using System.Web.Mvc;
using Point.Business.Logic;
using Point.Infrastructure.Attributes;

namespace Point.MVC.WebApplication.Controllers
{
    public class ContactInformationController : PointController
    {
        [ValidateAntiFiddleInjection("id")]
        public ActionResult TransferPointInformation(int id)
        {
            var department = DepartmentBL.GetTransferPointByLocation(uow, id);
            var model = ContactInformationViewBL.FromModel(uow, department);
            return PartialView("_ContactInformation", model);
        }

        [ValidateAntiFiddleInjection("id")]
        public ActionResult LocationInformation(int id)
        {
            var location = LocationBL.GetByID(uow, id);
            var model = ContactInformationViewBL.FromModel(uow, location);
            return PartialView("_ContactInformation", model);
        }

        [ValidateAntiFiddleInjection("id")]
        public ActionResult DepartmentInformation(int id)
        {
            var department = DepartmentBL.GetByDepartmentID(uow, id);
            var model = ContactInformationViewBL.FromModel(uow, department);
            return PartialView("_ContactInformation", model);
        }
    }
}

POINT/Source/Point.MVC.WebApplication/Controllers/ErrorController.cs
using Point.Infrastructure.Exceptions;
using System.Web.Mvc;

namespace Point.MVC.WebApplication.Controllers
{
    public class ErrorController : Controller
    {
        public ActionResult ErrorPage(ErrorViewModel model)
        {
            return View(model);
        }

        public ActionResult NotFound()
        {          
            return View();
        }
    }

}

POINT/Source/Point.MVC.WebApplication/Controllers/MenuController.cs
using DevTrends.MvcDonutCaching;
using Point.Business.Helper;
using Point.Business.Logic;
using Point.Database.CacheModels;
using Point.Database.Extensions;
using Point.Database.Models;
using Point.Models.Enums;
using Point.Database.Models.ViewModels;
using Point.Infrastructure.Extensions;
using Point.MVC.WebApplication.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Point.Database.Models.Constants;
using Point.Infrastructure.ProxiedMembership;
using Point.Models.LDM.EOverdracht30.Enums;

namespace Point.MVC.WebApplication.Controllers
{
    [DonutOutputCache(CacheProfile = "Short")]
    public partial class MenuController : PointController
    {
        public ActionResult Index(int id = -1)
        {
            var model = new MenuViewModel();

            setParents();

            var user = MembershipProxy.Instance.GetUser();
            if (user == null || string.IsNullOrEmpty(user.UserName))
            {
                return View(model); //return empty menu if user not logged in.
            }

            IList<LocalMenuItem> items = new List<LocalMenuItem>();

            model.IsError = parentController.Equals("Error", StringComparison.InvariantCultureIgnoreCase);
            model.IsSearch = HttpContext.Request.Path.ToLower().Contains("search");

            if (HttpContext.Request.IsManagementArea())
            {
                items = buildManagementMenu();
            }
            else
            {
                if (TransferID <= 0)
                {
                    if (!string.IsNullOrWhiteSpace(Request.GetParam("TransferID")))
                    {
                        return View(model);
                    }

                    if (parentAction.Equals("Participants", StringComparison.InvariantCultureIgnoreCase))
                    {
                        items = buildParticipantsMenu();
                    }
                    else if (parentAction.Equals("Search", StringComparison.InvariantCultureIgnoreCase))
                    {
                        if (ExternalPatientHelper.HavePatExternalReference())
                        {
                            items = buildExtReferenceMenu();
                        }
                        else
                        {
                            items = buildSearchMenu();
                        }
                    }
                    else if (model.IsError)
                    {
                        items = buildErrorMenu();
                    }
                    else if (parentController.Equals("Report", StringComparison.InvariantCultureIgnoreCase) || parentController.Equals("DownloadReport", StringComparison.InvariantCultureIgnoreCase))
                    {
                        items = buildReportMenu();
                    }
                }
                else
                {
                    items = buildFlowMenu(TransferID);
                    if (items == null)
                    {
                        return Content("<!-- Menu: Geen flow bekend -->");
                    }
                }
            }

            model.MenuItems = items;

            return View(model);
        }

        public ActionResult MobileHeaderMenu()
        {
            setParents();
            var flowinstance = FlowInstanceBL.GetByTransferID(uow, TransferID);

            var items = new List<LocalMenuItem>
            {
                new LocalMenuItem
                {
                    Glyphicon = "glyphicon glyphicon-home",
                    Description = "Home",
                    Disabled = false,
                    Label = "",
                    MenuType = MenuTypes.Actie,
                    Url = Url.Action("Overview", "Transfer")
                }
            };


            if (flowinstance != null)
            {
                var startphasedefinition = PhaseDefinitionCacheBL.GetBeginFlowPhaseDefinition(uow, flowinstance.FlowDefinitionID);

                items.Add(new LocalMenuItem
                {
                    Glyphicon = "glyphicon glyphicon-th-list",
                    Description = "Dashboard",
                    Disabled = false,
                    Label = "",
                    MenuType = MenuTypes.Actie,
                    Url = Url.Action("Dashboard", "FlowMain", new { TransferID })
                });

                items.Add(new LocalMenuItem
                {
                    Glyphicon = "glyphicon glyphicon-user gender-color-" + flowinstance?.Transfer?.Client?.Gender.GetDescription().ToLower(),
                    Description = "Patiëntinformatie",
                    Disabled = false,
                    Label = flowinstance.Transfer.Client.FullName(),
                    MenuType = MenuTypes.Actie,
                    Url = Url.Action("StartFlowForm", "FlowMain", new { TransferID, startphasedefinition.PhaseDefinitionID })
                });
            }

            return PartialView(items);
        }

        public ActionResult FormTabs()
        {
            setParents();
            var flowinstance = FlowInstanceBL.GetByTransferID(uow, TransferID);
            return buildFormTabs(flowinstance);
        }

        private IEnumerable<LocalMenuItem> GetManagementMenuItems()
        {
            var items = new List<LocalMenuItem>();

            var pointUserInfo = PointUserInfo();
            if (!pointUserInfo.HasManagementFunctions)
            {
                return items;
            }

            items.Add(new LocalMenuItem
            {
                Glyphicon = "glyphicon glyphicon-edit",
                Description = "Beheer functies",
                Disabled = false,
                Identifier = "Beheer",
                IsCurrent = parentAction == "Beheer",
                Label = "Beheer",
                MenuType = MenuTypes.Actie,
                Url = Url.Content("~/Management")
            });

            if (parentController == "Organization")
            {
                var onlyorganizations = this.HttpContext.Request.GetRequestVariable<bool>("onlyorganizations", false);

                items.Add(new LocalMenuItem
                {
                    Glyphicon = "glyphicon glyphicon-th-list",
                    Description = "Organisaties beheer",
                    Disabled = false,
                    Identifier = "Organisaties beheer",
                    IsCurrent = parentAction == "Index" && onlyorganizations == false,
                    Label = "Organisaties beheer",
                    MenuType = MenuTypes.Actie,
                    Url = Url.Content("~/Management/Organization")
                });

                items.Add(new LocalMenuItem
                {
                    Glyphicon = "glyphicon glyphicon-th-list",
                    Description = "Organisaties overzicht",
                    Disabled = false,
                    Identifier = "Organisaties overzicht",
                    IsCurrent = parentAction == "Index" && onlyorganizations,
                    Label = "Organisaties overzicht",
                    MenuType = MenuTypes.Actie,
                    Url = Url.Content("~/Management/Organization?onlyorganizations=true")
                });

                items.Add(new LocalMenuItem
                {
                    Glyphicon = "glyphicon glyphicon-th-list",
                    Description = "Afdeling rapport",
                    Disabled = false,
                    Identifier = "Afdeling rapport",
                    IsCurrent = parentAction == "DepartmentReport",
                    Label = "Afdeling rapport",
                    MenuType = MenuTypes.Actie,
                    Url = Url.Content("~/Management/Organization/DepartmentReport")
                });
            }

            return items;
        }

        #region Fields

        private string parentAction = "";
        private string parentController = "";
        private string parentSubcategory = "";
        private IList<LocalMenuItem> menuItems = new List<LocalMenuItem>();

        #endregion

        #region Private impl.

        private void setParents()
        {
            if (ControllerContext.ParentActionViewContext == null)
            {
                return;
            }

            parentAction = ControllerContext.ParentActionViewContext.RouteData.Values["action"].ToString();
            parentController = ControllerContext.ParentActionViewContext.RouteData.Values["controller"].ToString();
        }

        private void addMenuItem(PhaseDefinitionCache phasedefinition, List<PhaseInstance> phaseinstances, MenuItemDestination menuitemdestination, PointUserInfo userinfo)
        {
            var buildingtabs = menuitemdestination == MenuItemDestination.FormTab;

            var menutype = MenuHelper.GetMenuTypeFromMaincategory(phasedefinition.Maincategory);
            if (string.IsNullOrWhiteSpace(menutype))
            {
                return;
            }

            //No doubles on PhaseDefinitionID or Subcategory
            string identifier = String.Concat(menutype, phasedefinition.PhaseDefinitionID);
            if (menuItems.Any(mi => mi.Identifier == identifier || (!buildingtabs && mi.Label == phasedefinition.Subcategory)))
            {
                return;
            }

            //If zorgadvies check for "Ja"
            if (phasedefinition.FormTypeID == (int)FlowFormType.ZorgAdvies)
            {
                var zorgAdviesToevoegen = FlowFieldValueBL.GetByTransferIDAndFieldID(uow, TransferID, FlowFieldConstants.ID_ZorgAdviesToevoegen).FirstOrDefault();
                if (zorgAdviesToevoegen == null || (zorgAdviesToevoegen.Value != "Ja"))
                {
                    return;
                }
            }

            //Check standard rights
            var menuvisablility = MenuBL.GetMenuItemStatus(uow, phasedefinition, phaseinstances, userinfo, menuitemdestination);

POINT/Source/Point.MVC.WebApplication/Controllers/PageLockController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DevTrends.MvcDonutCaching;
using Point.Business.Logic;
using Point.Infrastructure.Extensions;

namespace Point.MVC.WebApplication.Controllers
{
    public class PageLockController : PointController
    {
        public ActionResult Timeout(Uri UrlReferrer)
        {
            if (string.IsNullOrWhiteSpace(UrlReferrer?.Query))
            {
                return PartialView();
            }

            var formType = FormTypeBL.GetByURL(uow, UrlReferrer);
            if (formType == null || !formType.HasPageLocking)
            {
                return PartialView();
            }

            ViewBag.FormName = formType.Name;

            var actionParams = HttpUtility.ParseQueryString(UrlReferrer.Query);
            var queryparameters = actionParams.AllKeys
                .ToDictionary(k => k.ToLowerInvariant(), k => actionParams[k])
                .Where(kv => !string.IsNullOrWhiteSpace(kv.Value))
                .Select(kv => kv).ToDictionary(kv => kv.Key, kv => kv.Value);

            if (!queryparameters.ContainsKey("formtypeid"))
            {
                queryparameters.Add("formtypeid", formType.FormTypeID.ToString());
            }

            if (!queryparameters.ContainsKey("formsetversionid"))
            {
                var formsetversion =
                    FormSetVersionBL.GetByTransferIDAndFormTypeID(uow, TransferID, formType.FormTypeID)
                        .OrderByDescending(fsv => fsv.CreateDate)
                        .FirstOrDefault();
                if (formsetversion != null)
                {
                    queryparameters.Add("formsetversionid", formsetversion.FormSetVersionID.ToString());
                }
            }

            if (queryparameters.ContainsKey("phasedefinitionid") && !queryparameters.ContainsKey("phaseinstanceid"))
            {
                if (int.TryParse(queryparameters["phasedefinitionid"], out int phasedefinitionid))
                {
                    var phaseinstance = PhaseInstanceBL.GetLastByTransferAndPhaseDefinition(uow, TransferID, phasedefinitionid);
                    if (phaseinstance != null)
                    {
                        queryparameters.Add("phaseinstanceid", phaseinstance.PhaseInstanceID.ToString());
                    }
                }
            }

            ViewBag.Url = Url.Action("StartFlowForm", "FlowMain", queryparameters.ToRouteValueDictionary());
            return PartialView();
        }

        public ActionResult Locked(int pageLockID)
        {
            var pageLock = PageLockBL.GetByID(uow, pageLockID);
            if (pageLock == null)
            {
                return PartialView();
            }

            var userinfo = PointUserInfo();

            return PartialView(PageLockViewBL.FromModel(uow, pageLock, userinfo));
        }

        [DonutOutputCache(Duration = 0)]
        public ActionResult RemovePageLockFromSession()
        {
            PageLockBL.DeleteBySessionID(uow, System.Web.HttpContext.Current.Session.SessionID);
            return Json(new {Status = "OK"}, JsonRequestBehavior.AllowGet);
        }

        [DonutOutputCache(Duration = 0)]
        public ActionResult RemovePageLockByID(int pagelockid)
        {
            PageLockBL.DeleteByPageLockID(uow, pagelockid);
            return Json(new { Status = "OK" }, JsonRequestBehavior.AllowGet);
        }
    }
}

POINT/Source/Point.MVC.WebApplication/Controllers/PhaseMainController.cs
using System.Web.Mvc;
using Point.MVC.WebApplication.Helpers;

namespace Point.MVC.WebApplication.Controllers
{
    public class PhaseMainController : PointController
    {
        public ActionResult Index()
        {
            return RedirectToAction("PhaseButtons");
        }

        public ActionResult PhaseButtons()
        {
            var viewModel = PhaseMainViewModelHelper.GetPhaseButtonsViewModel(this, GetGlobalProperties(getPhaseInstance: true));

            if (viewModel.HasErrors)
            {
                return Content(viewModel.ErrorMessage);
            }

            return PartialView("_PhaseButtons", viewModel);
        }
         

    }
}

POINT/Source/Point.MVC.WebApplication/Views/Shared/_Client_Header_Mobile.cshtml
@model ClientHeaderViewModel

<style type="text/css">
    #clientinfo {
        float: left;
    }

    #clientinfo a {
        color: white;
    }

    #clientinfo li, #loginBox li {
        font-size: 120%;
    }

    #clientname {
        font-weight: bold;
        margin-left: 7px;
    }

    #clientbirthdate {
        margin-left: 7px;
    }

    #loginBox {
        float: right;
        max-width: 50%;
    }

    #clientinfo {
        max-width: 50%;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
        vertical-align: top;
    }
</style>

<div class="header">
    <div class="container-fluid">
        <div id="clientinfo" class="color-pt-white">
            @if(!Model.IsMFAScreen)
            {
                @Html.Action("MobileHeaderMenu", "Menu", new { Model.Global.TransferID })
            }
        </div>
        
        <div class="header-clientbox actions noprint" id="loginBox">
            @{
                var login = Html.ActionLink(" ", "Login", "Login", null, new { @class = "glyphicon glyphicon-log-on color-pt-white" });
                var logoff = Html.ActionLink(" ", "Logoff", "Login", null, new { @class = "glyphicon glyphicon-log-out color-pt-white" });
                var loginLogoff = Model.HasUserName ? logoff : login;
            }
            <ul class="list-inline">
                @if(!Model.IsMFAScreen)
                {
                    <li class="color-pt-white" id="signaleringstatus" data-flowinstanceid="@Model.FlowInstanceID">@Html.Partial("_CurrentSignaleringStatus", Model.SignaleringStatusViewModel)</li>
                    if (Model.Global.TransferID > 0)
                    {
                        <li class="color-pt-white"><a class="glyphicon glyphicon-print color-pt-white" href="@Url.Action("Print", "PrintAction", new { Model.Global.TransferID })"></a></li>
                    }
                }
                <li class="color-pt-white">@loginLogoff</li>
            </ul>
        </div>
    </div>
</div>

POINT/Source/Point.MVC.WebApplication/Views/Shared/_CompanyLogo.cshtml
@model CompanyLogoViewModel
<div class="CompanyLogoContainer">
    <img src="@Model.LogoPath" class="CompanyLogo" />
</div>

POINT/Source/Point.MVC.WebApplication/Views/Shared/_PointDefaultLayoutBootstrap.cshtml
@using DevTrends.MvcDonutCaching
@using Point.MVC.WebApplication.Extensions
@using Point.Infrastructure.Helpers
@{ 
    var pointlogo = ConfigHelper.GetAppSettingByName("PointLogo", "Point-HighRes-Trans.png");
}
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html class="ie6 ielt9" style="min-width:1200px;"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7 ielt9" style="min-width:1200px;"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8 ielt9" style="min-width:1200px;"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" style="min-width:1200px;"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html style="min-width:1200px;">
<!--<![endif]-->
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title</title>
    @Html.Partial("_PointDefaultFavicon")

    <script>
        var appPath = '@ViewBag.AppPath';
        var areyousure = @((string)ViewBag.AreYouSure?? "false");
        var dashboardUrl = '@Html.Raw(Url.Action("Dashboard", "FlowMain", new {ViewBag.TransferID, Timeout = true }))';
        var removePageLockFromSessionUrl = '@Html.Raw(Url.Action("RemovePageLockFromSession", "PageLock"))';
        var removePageLockByIDUrl = '@Html.Raw(Url.Action("RemovePageLockByID", "PageLock"))';
        var readonly = @(ViewData["ReadMode"]?.ToString().ToLower() ?? "false");

        var hasPageLockTimer = @(ViewData.HasPageLocking().ToString().ToLower());
        var pageLockTimeoutTimer = @(ViewData.PageLockTimer());
        var isPageLocked = @(ViewData.IsPageLock().ToString().ToLower());
    </script>

    @Scripts.Render("~/Bundles/Scripts/PointDefault")
    @Styles.Render("~/Bundles/Styles/PointDefault")
    <style type="text/css">
        .left-menu {
            width: 220px;
            float:left;
        }
        .main-content {
            margin-left: 236px;
            overflow: hidden;
        }
    </style>
    <!--[if lt IE 9]>
        @Scripts.Render("~/Bundles/Scripts/BootstrapIE8")
    <![endif]-->
    @if (ConfigHelper.GetAppSettingByName("NoIndex", false))
    {
        <meta name="robots" content="noindex">
    }
</head>

<body role="document">
    <div class="container-fluid">
        <div class="left-menu">
            <div style="margin:15px;">
                <img src="~/Images/@pointlogo" style="vertical-align:middle;width:100%;max-width:160px;" title="POINT - Punt voor Overdracht, Informatie, Naslag en Transfers [@Environment.MachineName]" />
            </div>
            @Html.Action("Index", "Menu", new { area = "" }, excludeFromParentCache: true)
        </div>
        <div class="main-content">
            @Html.Action("Header", "Client", new { area = "" })

            @if (Html.ViewData.IsPageLock())
            {
                Html.RenderAction("Locked", "PageLock", new { area = "", ViewBag.TransferID, ViewBag.PageLockID });
            }
            @if ((string)ViewContext.RouteData.DataTokens["area"] != "Management")
            {
                @Html.Action("PhaseButtons", "PhaseMain", new { area = "" }, excludeFromParentCache: true)
            }
            @Html.Action("FormTabs", "Menu", new { area = "" }, excludeFromParentCache: true)

            @{
                if (!String.IsNullOrWhiteSpace(ViewBag.Header))
                {
                    <h1 class="page-header">@ViewBag.Header</h1>
                }
            }

            <div id="error" style="display:none;" class="alert alert-dismissible alert-danger" role="alert">Er ging iets mis.<br /><div id="errormessage" style="font-weight:bold;"></div><br /><span onclick="location.reload()">Klik hier om de pagina opnieuw te laden en probeer het opnieuw.</span></div>
            <div id="success" style="display:none;" class="alert alert-dismissible alert-success" role="alert">Succesvol voltooid.<br /><div id="successmessage" style="font-weight:bold;"></div></div>
            <div id="warning" style="display:none;" class="alert alert-dismissible alert-warning" role="alert">Belangrijk<br /><div id="warningmessage" style="font-weight:bold;"></div><br /></div>
            <div id="modal" class="modal" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-body">
                        </div>
                    </div>
                </div>
            </div>
            <div id="signalmodal" class="modal" role="dialog" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-body">
                        </div>
                    </div>
                </div>
            </div>
            <div id="mainContainer">
                @RenderBody()
            </div>
            <div class="modal" id="loader" aria-hidden="true">
                <div class="modal-dialog modal-sm">
                    <div class="modal-content">
                        <div class="modal-body">
                            <div style="height:100px;">
                                <img style="float:left;margin-right:20px;height:100px" src="@Url.Content("~/Images/PointLoading.gif")" />
                                <br />
                                Uw gegevens zijn ontvangen.<br />
                                Even geduld a.u.b.
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="modal" id="errormodal" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">Er is een fout opgetreden</div>
                        <div class="modal-body">

                        </div>
                        <div class="modal-footer">
                            <button type="button" data-dismiss="modal" class="btn">Sluiten</button>
                        </div>
                    </div>
                </div>
                <input type="hidden" id="setFocusOnErrorModalClose" />
            </div>

            <div class="modal" id="prefillmodal" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">Let op:</div>
                        <div class="modal-body">
                            <div id="defaultprefilltext" style="display:none;">
                                Dit formulier is voorgevuld met gegevens uit andere formulieren in dit transferdossier.
                                De voorgevulde velden hebben een gele kleur. U wordt geadviseerd om de actualiteit van de gegevens van alle voorgevulde velden te controleren om deze indien nodig aan te passen c.q. verwijderen.
                            </div>
                            <div id="epdprefilltext" style="display:none;">
                                <p>
                                    Dit formulier is voorgevuld met gegevens uit andere formulieren van dit POINT transferdossier en met gegevens afkomstig uit het EPD/EVD van uw organisatie.
                                    <ul>
                                        <li>De uit het POINT transferdossier voorgevulde velden hebben een gele kleur.</li>
                                        <li>De uit het EPD/EVD voorgevulde velden hebben een blauw kleur</li>
                                    </ul>
                                    U wordt geadviseerd om de actualiteit van de gegevens van alle voorgevulde velden te controleren om deze indien nodig aan te passen c.q. verwijderen. Indien u een blauw gekleurd veld bewerkt krijgt deze een witte kleur. Dat betekent dat dit veld niet meer wordt geupdate. Alleen blauwe gekleurde velden worden geupdate als op de knop <b>Update uit EVD/EPD</b> in dit formulier klikt.
                                    Geel gekleurde velden worden nooit geupdate. Wanneer het formulier de volgende keer wordt geopende zijn de gele kleuren verdwenen.
                                </p>
                            </div>
                            <div id="savedepdprefilltext" style="display:none;">
                                Dit formulier is initieel voorgevuld met o.a. gegevens afkomstig uit het EPD/EVD van uw organisatie. Deze zijn herkenbaar aan de blauw gekleurde velden. U kunt deze velden updaten door op de knop <b>Update uit EVD/EPD</b> te klikken. Indien u een blauw gekleurd veld bewerkt krijgt deze een witte kleur. Dat betekent dat dit veld niet meer wordt geupdate. Alleen blauw velden worden geupdate.
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" data-dismiss="modal" class="btn">Sluiten</button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

    @RenderSection("scripts", false)
</body>
</html>

POINT/Source/Point.MVC.WebApplication/Views/Shared/_PointDefaultLayoutMobile.cshtml
@using DevTrends.MvcDonutCaching
@using Point.MVC.WebApplication.Extensions
@using Point.Infrastructure.Helpers
@{
    var pointlogo = ConfigHelper.GetAppSettingByName<string>("PointLogo", "Point-HighRes-Trans.png");
}

<!DOCTYPE html>
<html lang="nl">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@ViewBag.Title</title>
    @Html.Partial("_PointDefaultFavicon")

    <script>
        var appPath = '@ViewBag.AppPath';
        var areyousure = @((string)ViewBag.AreYouSure?? "false");
        var dashboardUrl = '@Html.Raw(Url.Action("Dashboard", "FlowMain", new {ViewBag.TransferID, Timeout = true }))';
        var removePageLockFromSessionUrl = '@Html.Raw(Url.Action("RemovePageLockFromSession", "PageLock"))';
        var removePageLockByIDUrl = '@Html.Raw(Url.Action("RemovePageLockByID", "PageLock"))';
        var readonly = @(ViewData["ReadMode"] == null ? "false" : ViewData["ReadMode"].ToString().ToLower());

        var hasPageLockTimer = @(ViewData.HasPageLocking().ToString().ToLower());
        var pageLockTimeoutTimer = @(ViewData.PageLockTimer());
        var isPageLocked = @(ViewData.IsPageLock().ToString().ToLower());
    </script>

    @Scripts.Render("~/Bundles/Scripts/PointDefault")
    @Styles.Render("~/Bundles/Styles/PointDefault")
    @if (ConfigHelper.GetAppSettingByName("NoIndex", false))
    {
        <meta name="robots" content="noindex">
    }
</head>

<body>

    <nav class="navbar navbar-fixed-top">
        @Html.Action("Header", "Client")
    </nav>

    <div class="container-fluid" style="padding-top: 60px;">
        @if (Html.ViewData.IsPageLock())
        {
            Html.RenderAction("Locked", "PageLock", new { area = "", ViewBag.TransferID, ViewBag.PageLockID });
        }
        @Html.Action("PhaseButtons", "PhaseMain", excludeFromParentCache: true)
        <div id="error" style="display:none;" class="alert alert-dismissible alert-danger" role="alert">Er ging iets mis.<br /><div id="errormessage" style="font-weight:bold;"></div><br /><span onclick="location.reload()">Klik hier om de pagina opnieuw te laden en probeer het opnieuw.</span></div>
        <div id="success" style="display:none;" class="alert alert-dismissible alert-success" role="alert">Succesvol voltooid.<br /><div id="successmessage" style="font-weight:bold;"></div></div>
        <div id="modal" class="modal" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-body">
                    </div>
                </div>
            </div>
        </div>
        <div id="signalmodal" class="modal" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-body">
                    </div>
                </div>
            </div>
        </div>
        <div id="mainContainer">
            @RenderBody()
        </div>
        <div class="modal" id="loader" aria-hidden="true">
            <div class="modal-dialog modal-sm">
                <div class="modal-content">
                    <div class="modal-body">
                        <div style="height:100px;">
                            <img style="float:left;margin-right:20px;height:100px" src="@Url.Content("~/Images/PointLoading.gif")" />
                            <br />
                            Uw gegevens zijn ontvangen.<br />
                            Even geduld a.u.b.
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal" id="errormodal" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">Er is een fout opgetreden</div>
                    <div class="modal-body">

                    </div>
                    <div class="modal-footer">
                        <button type="button" data-dismiss="modal" class="btn">Sluiten</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>