POINT/Source/Point.MVC.WebApplication/Areas/Management/Controllers/OrganizationController.cs
using DevTrends.MvcDonutCaching;
using Point.Models.Enums;
using Point.Database.Models.ViewModels;
using Point.Infrastructure.Attributes;
using Point.MVC.WebApplication.Attributes;
using Point.MVC.WebApplication.Controllers;
using System.Web.Mvc;
using Point.MVC.WebApplication.Helpers;

namespace Point.MVC.WebApplication.Areas.Management.Controllers
{
    [DonutOutputCache(Duration = 0)]
    public class OrganizationController : PointController
    {
        [FunctionRoles(FunctionRoleTypeID.ManageAll, FunctionRoleTypeID.ManageOrganization)]
        [ValidateOrigin]
        public ActionResult DepartmentReport()
        {
            return View();
        }

        [FunctionRoles(FunctionRoleTypeID.ManageAll, FunctionRoleTypeID.ManageOrganization)]
        public ActionResult Index(string search, bool searchDeleted = false, bool onlyOrganizations = false)
        {
            var viewmodel = OrganizationManagementViewModelHelper.GetIndexViewModel(this, search, searchDeleted, onlyOrganizations);
            return View(viewmodel);
        }

        [FunctionRoles(FunctionRoleTypeID.ManageAll, FunctionRoleTypeID.ManageOrganization)]
        public PartialViewResult List(string search, bool searchDeleted = false, bool onlyOrganizations = false)
        {
            var viewmodel = OrganizationManagementViewModelHelper.GetListViewModel(this, search, searchDeleted, onlyOrganizations);
            return PartialView(viewmodel);
        }

        [HttpGet]
        [FunctionRoles(FunctionRoleLevelID.Organization, FunctionRoleTypeID.ManageAll, FunctionRoleTypeID.ManageOrganization)]
        public ActionResult Create()
        {
            var viewmodel = OrganizationManagementViewModelHelper.GetOrganizationEditViewModel(this, null);
            return PartialView("Edit", viewmodel);
        }

        [HttpGet]
        [FunctionRoles(FunctionRoleLevelID.Organization, FunctionRoleTypeID.ManageAll, FunctionRoleTypeID.ManageOrganization)]
        [ValidateAntiFiddleInjection("OrganizationID")]
        public ActionResult Edit(int organizationID)
        {
            var viewmodel = OrganizationManagementViewModelHelper.GetOrganizationEditViewModel(this, organizationID);
            return PartialView(viewmodel);
        }

        [HttpPost]
        [FunctionRoles(FunctionRoleLevelID.Organization, FunctionRoleTypeID.ManageAll, FunctionRoleTypeID.ManageOrganization)]
        [ValidateAntiForgeryToken]
        [ValidateAntiFiddleInjection("OrganizationID")]
        public ActionResult Save(OrganizationViewModel viewModel)
        {
            var jsonObject = OrganizationManagementViewModelHelper.Save(this, viewModel);
            return Json(jsonObject);
        }
        
        [ValidateAntiFiddleInjection("OrganizationID")]
        [FunctionRoles(FunctionRoleTypeID.ManageAll, FunctionRoleTypeID.ManageOrganization, FunctionRoleTypeID.ManageOrganization)]
        public ActionResult UpdateOrganizationLogo(int organizationID)
        {
            var jsonObject = OrganizationManagementViewModelHelper.UpdateOrganizationLogo(this, organizationID);
            return Json(jsonObject);
        }

        [ValidateAntiFiddleInjection("OrganizationID")]
        [FunctionRoles(FunctionRoleTypeID.ManageAll, FunctionRoleTypeID.ManageOrganization, FunctionRoleTypeID.ManageOrganization)]
        public ActionResult EditOrganizationLogo(int organizationID)
        {
            return View();
        }

        [ValidateAntiFiddleInjection("OrganizationID")]
        [FunctionRoles(FunctionRoleTypeID.ManageAll, FunctionRoleTypeID.ManageOrganization)]
        public JsonResult DeleteOrganizationLogo(int organizationID)
        {
            var jsonObject = OrganizationManagementViewModelHelper.DeleteOrganizationLogo(this, organizationID);
            return Json(jsonObject, JsonRequestBehavior.AllowGet);
        }

    }
}

POINT/Source/Point.MVC.WebApplication/Controllers/OrganizationController.cs
using System.Web.Mvc;
using Point.Business.Logic;
using Point.Database.Models.ViewModels;
using Point.Infrastructure.Attributes;
using Point.MVC.WebApplication.Helpers;

namespace Point.MVC.WebApplication.Controllers
{
    public class OrganizationController : PointController
    {
        [ValidateAntiFiddleInjection("departmentid")]
        public ActionResult DepartmentDetails(int departmentid)
        {
            var department = DepartmentBL.GetByDepartmentID(uow, departmentid);
            return new SecureActionResult(department, Request.IsAjaxRequest());
        }

        public JsonResult DeleteInvite(int organizationinviteid)
        {
            var success = OrganizationInviteBL.Delete(uow, organizationinviteid);

            return Json(new {Success = success}, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Participants(OrganizationParticipantsViewModel viewmodel)
        {
            viewmodel = OrganizationViewModelHelper.GetParticipantsViewModel(viewmodel, PointUserInfo());

            return new SecureActionResult("Participants", viewmodel, Request.IsAjaxRequest());
        }
    }
}

POINT/Source/Point.MVC.WebApplication/Areas/Management/Views/Organization/Edit.cshtml
@model OrganizationViewModel
@using Point.Infrastructure.Attributes
@using Point.Models.Enums

@{
    var digestOrgSel = new { Digest = AntiFiddleInjection.CreateDigest(Model.OrganizationID), organizationid = Model.OrganizationID };
    var digestOrg = new { Digest = AntiFiddleInjection.CreateDigest(Model.OrganizationID) };
    var organizationSaveUrl = Url.Action("Save", "Organization", digestOrg);
}

<script type="text/javascript">
    var formID = "#editorganizationform";

    var _OrganizationEdit = {
        FormID: formID,
        Urls : {
            DeleteLogo: '@Html.Raw(Url.Action("DeleteOrganizationLogo", "Organization", digestOrgSel))',
            EditLogo: '@Html.Raw(Url.Action("EditOrganizationLogo", "Organization", digestOrgSel))',
            GetLogo: '@Html.Raw(Url.Action("GetByOrganizationID", "OrganizationLogo", new { Area = "", Model.OrganizationID, digest = @AntiFiddleInjection.CreateDigest(Model.OrganizationID) }))',
            ServiceAreas: '@Url.Action("ServiceAreas", "ServiceArea", new { Area = "Management" })',
            UploadLogo: '@Html.Raw(Url.Action("UpdateOrganizationLogo", "Organization", digestOrgSel))'
        },
        OrganizationTypeHospital: @((int)OrganizationTypeID.Hospital),
        OrganizationTypeVVT: @((int)OrganizationTypeID.HealthCareProvider)
    };

    initializevalidation(formID);

    $.validator.setDefaults({ ignore: '.ignore *' });
    $.validator.unobtrusive.parse($(formID));

    function SaveForm(sender, close) {
        if ($(formID).valid()) {
            var url = $(sender).data("saveurl");
            var callback = function (data) {
                if (close) {
                    $("#modal").modal('hide');
                } else {
                    $("#savedmessage").show();
                    RefreshOrganizationData(data);
                    setTimeout(function () { $("#savedmessage").hide(); }, 3000);
                }
            }
            AjaxSave($(sender).closest("form"), url, false, callback, true, null);
        }
    }

    function RefreshOrganizationData(data) {
        if (!data) return;
        $("#OrganizationID").val(data.OrganizationID);
        $(":hidden[name='Digest']").val(data.Digest);
        $('button[data-saveurl]').data("saveurl", "/Management/Organization/Save?Digest=" + data.Digest);

        if (data.OrganizationProjects) {
            for (var i = 0; i < data.OrganizationProjects.length; i++) {
                var project = data.OrganizationProjects[i];
                $("#tbodyorganizationproject input[data-property='name'][value='" + project.Name + "']:hidden").prev("input[data-property='organizationprojectid']:hidden").val(project.OrganizationProjectID);
            }
        };
    }

    function LoadServiceAreas() {
        var organizationID = $("#OrganizationID").val();

        $.ajax({
            method: "POST",
            url: _OrganizationEdit.Urls.ServiceAreas,
            data: { OrganizationID: organizationID },
            success: function (data) { $("#serviceareas").html(data) },
            error: function (jqXHR, status) {
                $("#serviceareas").html(jqXHR.responseJSON.ErrorMessage);
            }
        });
    }

    $(function() {
        $('[data-toggle="clickover"]:not(.client-header)').clickover(
            {
                html: true,
                placement: "top",
                global_close: true,
                esc_close: true,
                title: $(this).data("title"),
                content: $(this).data("content")
            });
    });
</script>

@* This must be executed AFTER the above script! *@
@Scripts.Render("~/Bundles/Scripts/Management/OrganizationEdit")


<style type="text/css">
    .signature {
        width: 156px;
        height: 64px;
        border: 1px solid #e5e5e5;
    }

    .form-buttons {
        margin-top: 20px;
    }

        .form-buttons .btn {
            min-width: 100px;
        }

    .alert-button {
        padding-top: 3px;
        padding-bottom: 5px;
    }
</style>

<ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
        <a href="#details" data-toggle="tab" aria-controls="details" role="tab" title="Organisatie">
            Organisatie
        </a>
    </li>
    <li role="presentation">
        <a href="#adminsettings" data-toggle="tab" aria-controls="adminsettings" role="tab" title="Beheer instellingen">
            Beheer instellingen
        </a>
    </li>
    <li role="presentation" class="serviceareas" style="@(Model.EnableServiceAreas ? "" : "display:none;")">
        <a href="#serviceareas" data-toggle="tab" aria-controls="serviceareas" role="tab" title="Bedienings gebieden" onclick="LoadServiceAreas();">
            Bedienings gebieden
        </a>
    </li>
    <li role="presentation" class="organizationprojects">
        <a href="#organizationprojects" data-toggle="tab" aria-controls="projects" role="tab" title="Dossierkenmerken">
            Dossierkenmerken
        </a>
    <li role="presentation">
        <a href="#coupling" data-toggle="tab" aria-controls="coupling" role="tab" title="Koppeling instellingen">
            Koppeling / SSO
        </a>
    </li>
    <li role="presentation" class="formtypes" style="@(Model.EnableFormTypeOrganizationTab ? "" : "display:none;")">
        <a href="#formtypes" data-toggle="tab" aria-controls="formtypes" role="tab" title="Formulier(en)">
            Formulier(en)
        </a>
    </li>
    <li role="presentation">
        <a href="#history" data-toggle="tab" aria-controls="history" role="tab" title="Historie">
            Historie
        </a>
    </li>
</ul>

<form class="form-horizontal" id="editorganizationform" action="@Url.Action("Save")" method="post">
    @Html.AntiForgeryToken()
    @Html.AntiFiddleTokenFor(m => m.OrganizationID)
    @Html.HiddenFor(m => m.OrganizationID)
    <div class="tab-content">
        <div class="tab-pane active" role="tabpanel" id="details">
            <h3>Organisatie</h3>
            @Html.Partial("_OrganizationDetails", Model)
        </div>
        <div class="tab-pane" role="tabpanel" id="adminsettings">
            <h3>Beheer instellingen</h3>
            @Html.Partial("_OrganizationSettings", Model)
        </div>
        <div class="tab-pane serviceareas" role="tabpanel" id="serviceareas" style="@(Model.EnableServiceAreas ? "" : "display:none;")"></div>
        <div class="tab-pane organizationprojects" role="tabpanel" id="organizationprojects">
            <h3>Dossierkenmerken</h3>
            @Html.Partial("_OrganizationProjects", Model)
        </div>
        <div class="tab-pane" role="tabpanel" id="coupling">
            <h3>Koppeling / SSO</h3>
            @Html.Partial("_OrganizationCoupling", Model)
        </div>
        <div class="tab-pane formtypes" role="tabpanel" id="formtypes" style="@(Model.EnableFormTypeOrganizationTab ? "" : "display:none;")">
            <h3>Formulier(en)</h3>
            @Html.Partial("_OrganizationFormTypes", Model)
        </div>
        <div class="tab-pane" role="tabpanel" id="history">
            <h3>Historie</h3>
            @Html.Partial("_GenericLog", new GenericLogViewModel { TableName = "Organization", PrimaryKey = Model.OrganizationID.ToString() })
        </div>
        <div class="clearfix"></div>
    </div>

    <div class="form-buttons clearfix">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Annuleren</button>
        <span class="pull-right">
            <span class="alert alert-success alert-button" style="display: none;" id="savedmessage">Opgeslagen</span>
            <button type="button" class="btn btn-default" data-saveurl="@organizationSaveUrl" onclick="SaveForm(this, false)">Opslaan</button>
            <button type="button" class="btn btn-primary" data-saveurl="@organizationSaveUrl" onclick="SaveForm(this, true)">Opslaan en sluiten</button>
        </span>
    </div>
</form>

POINT/Source/Point.MVC.WebApplication/Areas/Management/Views/Organization/EditOrganizationLogo.cshtml
@using (Html.BeginForm("EditOrganizationLogo", "Organization", FormMethod.Post, new { id = "organizaitonlogoform", enctype = "multipart/form-data", @class = "form-horizontal" }))
{
    <div class="modal-header">
        <h4 class="modal-title">Organisatie logo</h4>
    </div>
    <div class="modal-body" id="modalBody">
        <div class="form-group">
            <div class="text-center">
                <img id="imgpreviewlogo" class="signature" src="~/Images/nosignature.png" />
            </div>
        </div>
        <div class="form-group">
            <div class="text-center">
                <label class="btn btn-primary" for="btnpreviewlogo">
                    <input id="btnpreviewlogo" type="file" name="file" style="display:none;">
                    Selecteer bestand
                </label>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Annuleren</button>
        <button type="button" class="btn btn-primary" id="uploadlogo">Opslaan</button>
    </div>
}

POINT/Source/Point.MVC.WebApplication/Areas/Management/Views/Organization/Index.cshtml
@model OrganizationManagementViewModel

<link href="~/Content/bootstrap-multiselect-point.css" rel="stylesheet" />
@Scripts.Render("~/Bundles/Scripts/SearchMultiselect")
@Scripts.Render("~/Bundles/Scripts/FormType")
@Scripts.Render("~/Bundles/Scripts/JQueryForm")

<script>
    
    function searchOrganization(evt) {
        evt.preventDefault();
        var form = $(this).closest("form");
        AjaxLoad(form, form.attr("action"), "#organizationlist");
    }

    function setupOrganization() {
        var organizationProjectModalRef = "#organizationprojectmodal";

        $(organizationProjectModalRef).on("shown.bs.modal", function (e) {
            $(organizationProjectModalRef).find("#projectname").focus();
        });

        $("#searchbut").on("click", searchOrganization);

        $("#modal").on("hide.bs.modal", function (e) {
            //Zou niet hoeven maar doet anders toch refresh op #modal2.on("hide...");
            if (e.target.id === "modal") {
                $("#searchbut").trigger("click");
            }
        });
    }

    $(function() {
        setupOrganization();
    });

</script>

<div id="modal2" class="modal" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

<form id="formSearchOrganization" onsubmit="return false;" action="@Url.Action("List")" class="form-horizontal" method="post">
    @Html.Hidden("OnlyOrganizations", Model.OnlyOrganizations)
    <div class="panel panel-primary">
        <div class="panel-heading clearfix">
            Organisaties beheren
            <div class="checkbox pull-right">
                <label class="color-pt-white">@Html.CheckBox("searchdeleted", Model.SearchDeleted)Zoek in verwijderde organisaties / locaties / afdelingen</label>
            </div>
        </div>
        <div class="panel-body">
            <div class="form-group">
                <label class="control-label col-xs-3">Organisatie / Locatie / Afdeling</label>
                <div class="col-xs-5">
                    @Html.TextBox("Search", Model.Search, new { @class = "form-control" })
                </div>
                <div class="col-xs-2">
                    <input type="submit" id="searchbut" class="btn btn-block btn-primary" value="Zoeken">
                </div>
            </div>
        </div>
    </div>
</form>

<div class="clearfix">
    <span class="pull-right">
        @if (Model.HasRegionEditRights)
        {
            <button class="btn btn-primary" onclick="ShowModal('@Url.Action("Create", "Organization")')">Organisatie toevoegen</button>
        }
        @if (Model.HasOrganizationEditRights)
        {
            <button class="btn btn-primary" onclick="ShowModal('@Url.Action("Create", "Location")')">Locatie toevoegen</button>
        }
        @if (Model.HasLocationEditRights)
        {
            <button class="btn btn-primary" onclick="ShowModal('@Url.Action("Create", "Department")')">Afdeling toevoegen</button>
        }
    </span>
</div>

<div id="organizationlist" style="margin-top:15px;">
    @if (Model.OnlyOrganizations)
    {
        @Html.Partial("Organizations", Model)
    }
    else
    {
        @Html.Partial("List", Model)
    }
</div>

<div id="organizationprojectmodal" class="modal" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <div style="height:40px;">
                    <div class="form-group">
                        <label class="control-label col-xs-3" for="projectname">Naam</label>
                        <div class="col-xs-9">
                            <input class="form-control" id="projectname" name="projectname" type="text">
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn">Annuleren</button>
                <button type="button" data-dismiss="modal" class="btn btn-default" id="ok">Ok</button>
            </div>
        </div>
    </div>
</div>

<div id="organizationprojectdeletemodal" class="modal" role="dialog" aria-labelledby="basicModal" aria-hidden="true" title="Kenmerk verwijderen">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                Met het verwijderen van een kenmerk is dit kenmerk niet meer te koppelen aan dossiers. <br />
                <br />
                <b>Weet u het zeker?</b>
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn">Annuleren</button>
                <button type="button" data-dismiss="modal" class="btn btn-danger" id="delete">Verwijderen</button>
            </div>
        </div>
    </div>
</div>

<div id="autocreatesetDeleteModal" class="modal" role="dialog" aria-hidden="true" title="Autocreate set verwijderen">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <b>Autocreate set verwijderen</b>
            </div>
            <div class="modal-body">
                Wilt u deze autocreate set verwijderen?
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn">Nee</button>
                <button type="button" data-dismiss="modal" class="btn btn-primary" id="delete">Ja</button>
            </div>
        </div>
    </div>
</div>

<div id="organizationChoiceModal" class="modal" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <b>Organisatie keuze</b>
            </div>
            <div class="modal-body">
                U dient eerst een organisatie te kiezen
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn">Ok</button>
            </div>
        </div>
    </div>
</div>

<div id="deletelogomodal" class="modal" role="dialog" title="Organisatie logo" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Organisatie logo verwijderen</h4>
            </div>
            <div class="modal-body">
                <p>
                    <strong>Weet u het zeker?</strong>
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Annuleren</button>
                <button type="button" class="btn btn-danger" onclick="_OrganizationEdit.Functions.DeleteLogo(this)">Verwijderen</button>
            </div>
        </div>
    </div>
</div>

POINT/Source/Point.MVC.WebApplication/Areas/Management/Views/Organization/List.cshtml
@model OrganizationManagementViewModel

<style type="text/css">
    .clickable {
        cursor: pointer;
    }

    .semihide {
        opacity: 0.3;
    }

    .inactive {
        color: red;
    }

    table thead {
        width: 100%;
    }
</style>

<script type="text/javascript">
    $(document).ready(function () {
        var height = $(window).innerHeight() - $("#organizationlist").offset().top - 130;
        table = $("#organizationtable").DataTable({
            "paging": false,
            "order": [],
            "scrollY": height
        });
    });

    $(window).resize(function () {
        table.columns.adjust().draw();
        var height = $(window).innerHeight() - $("#organizationlist").offset().top - 130;
        $("#organizationtable").closest(".dataTables_scrollBody").height(height);
    });
</script>

<table class="table table-striped" id="organizationtable">
    <thead>
        <tr>
            <th width="25%">Organisatie</th>
            <th width="15%">Regio</th>
            <th width="20%">Type organisatie</th>
            <th width="20%">Locatie</th>
            <th width="20%">Afdeling/Zorgtype</th>
        </tr>
    </thead>
    <tbody>
        @{
            var inactiveItem = " <span class=inactive>(verwijderd)</span>";

            foreach (var row in Model.OrganizationLocationDepartments)
            {
                var editOrganizationClick = Model.HasOrganizationEditRights ? "onclick=ShowModal('" + Url.Action("Edit", "Organization", new { row.OrganizationID, Digest = AntiFiddleInjection.CreateDigest(row.OrganizationID) }) + "');" : "";
                var editLocationClick = row.IsLocationEditAllowed ? "onclick=ShowModal('" + Url.Action("Edit", "Location", new { row.LocationID, Digest = AntiFiddleInjection.CreateDigest(row.LocationID) }) + "');" : "";
                var editDepartmentClick = row.IsDepartmentEditAllowed ? "onclick=ShowModal('" + Url.Action("Edit", "Department", new { row.DepartmentID, Digest = AntiFiddleInjection.CreateDigest(row.DepartmentID) }) + "');" : "";

                var inactiveOrg = Html.Raw(row.OrganizationInactive ? inactiveItem : "");
                var inactiveLoc = Html.Raw(row.LocationInactive ? inactiveItem : "");
                var inactiveDep = Html.Raw(row.DepartmentInactive ? inactiveItem : "");

                var addLocation = row.IsLocationInsertAllowed ? Html.Raw(" <span class=\"glyphicon glyphicon-plus clickable color-pt-green\" title=\"Locatie toevoegen\" onclick=ShowModal('" + Url.Action("Create", "Location", new { row.OrganizationID, Digest = AntiFiddleInjection.CreateDigest(row.OrganizationID) }) + "');></span>") : Html.Raw("");
                var addDepartment = row.IsDepartmentInsertAllowed ? Html.Raw(" <span class=\"glyphicon glyphicon-plus clickable color-pt-green\" title=\"Afdeling toevoegen\" onclick=ShowModal('" + Url.Action("Create", "Department", new { row.OrganizationID, row.LocationID, Digest = AntiFiddleInjection.CreateDigest(row.LocationID) }) + "');></span>") : Html.Raw("");

                <tr>
                    <td @(row.ShowOrganization ? "" : "class=semihide")><span @(Model.HasOrganizationEditRights ? "class=clickable" : "") @editOrganizationClick>@row.OrganizationName@(inactiveOrg)</span>@addLocation</td>
                    <td @(row.ShowOrganization ? "" : "class=semihide")><span>@row.RegionName</span></td>
                    <td @(row.ShowOrganization ? "" : "class=semihide")><span>@row.OrganizationType</span></td>
                    <td @(row.ShowLocation ? "" : "class=semihide")><span @(row.IsLocationEditAllowed ? "class=clickable" : "") @editLocationClick>@row.LocationName@(inactiveLoc)</span>@addDepartment</td>
                    <td @(row.IsDepartmentEditAllowed ? "class=clickable" : "") @editDepartmentClick>@row.DepartmentName@(inactiveDep)</td>
                </tr>
            }
        }
    </tbody>
</table>

POINT/Source/Point.MVC.WebApplication/Areas/Management/Views/Organization/Organizations.cshtml
@model OrganizationManagementViewModel

<style type="text/css">
    .clickable {
        cursor: pointer;
    }

    .inactive {
        color: red;
    }

    .semihide {
        opacity: 0.3;
    }

    table thead {
        width: 100%;
    }
</style>

<script type="text/javascript">
    $(document).ready(function () {
        var height = $(window).innerHeight() - $("#organizationlist").offset().top - 130;
        table = $("#organizationtable").DataTable({
            "paging": false,
            "order": [],
            "scrollY": height
        });
    });

    $(window).resize(function () {
        table.columns.adjust().draw();
        var height = $(window).innerHeight() - $("#organizationlist").offset().top - 130;
        $("#organizationtable").closest(".dataTables_scrollBody").height(height);
    });
</script>

<table class="table table-striped" id="organizationtable">
    <thead>
        <tr>
            <th>Organisatie</th>
            <th>Locatie</th>
            <th>Regio</th>
            <th>Type organisatie</th>
            <th>Flows</th>
            <th>Verzendt</th>
            <th>Ontvangt</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var row in Model.OrganizationLocationDepartments)
        {
            var editOrganizationClick = Model.HasOrganizationEditRights ? "onclick=ShowModal('" + Url.Action("Edit", "Organization", new { row.OrganizationID, Digest = AntiFiddleInjection.CreateDigest(row.OrganizationID) }) + "');" : "";
            var editLocationClick = row.IsLocationEditAllowed ? "onclick=ShowModal('" + Url.Action("Edit", "Location", new { row.LocationID, Digest = AntiFiddleInjection.CreateDigest(row.LocationID) }) + "');" : "";

            var inactiveOrg = Html.Raw(row.OrganizationInactive ? " <span class=inactive>(verwijderd)</span>" : "");
            var inactiveLoc = Html.Raw(row.LocationInactive ? " <span class=inactive>(verwijderd)</span>" : "");

            <tr>
                <td @(Model.HasOrganizationEditRights ? "class=clickable" : "") @editOrganizationClick><span @(row.ShowOrganization ? "" : "class=semihide")>@row.OrganizationName@(inactiveOrg)</span></td>
                <td @(row.IsLocationEditAllowed ? "class=clickable" : "") @editLocationClick><span>@row.LocationName@(inactiveLoc)</span></td>
                <td><span>@row.RegionName</span></td>
                <td><span>@row.OrganizationType</span></td>
                <td @(row.IsLocationEditAllowed ? "class=clickable" : "") @editLocationClick>row.FlowDefinitionNames</td>
                <td class="text-center">@Html.Raw(row.IsSendingParty ? "<span class=\"glyphicon glyphicon-ok\" />" : "")</td>
                <td class="text-center">@Html.Raw(row.IsReceivingParty ? "<span class=\"glyphicon glyphicon-ok\" />" : "")</td>
            </tr>
        }
    </tbody>
</table>